import { RootState } from '@/store';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { MdOutlineClose } from 'react-icons/md';
import { useDispatch, useSelector } from 'react-redux';
import { actions } from '@/slices/cart';

export default function Cart() {
  const { products } = useSelector((state: RootState) => state.cart);
  const dispatch = useDispatch();
  return (
    <>
      <Head>
        <title>Matter - Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container grid grid-cols-12 items-start pb-16 pt-4 gap-6">
        <div className="table-cart col-span-12">
          <div className="table-cart-head grid grid-cols-12">
            <div className="col-span-2">Sku</div>
            <div className="col-span-2">Image</div>
            <div className="col-span-4">Product</div>
            <div className="col-span-1">Quantity</div>
            <div className="col-span-2">Total</div>
            <div className="col-span-1">Remove</div>
          </div>
          <div className="table-cart-body">
            {products.map((product, index) => (
              <div key={product._id + index} className="grid grid-cols-12">
                <div className="table-cart-body-col col-span-2">
                  {product.sku}
                </div>
                <div className="table-cart-body-col col-span-2">
                  <Link
                    href={{
                      pathname: '/product/[slug]',
                      query: {
                        slug: product.slug
                      }
                    }}
                  >
                    <Image
                      src={product.thumbnail}
                      width={200}
                      height={50}
                      className="max-w-[200px] w-full h-auto"
                      alt={product.alt}
                    />
                  </Link>
                </div>
                <div className="table-cart-body-col col-span-4">
                  <Link
                    href={{
                      pathname: '/product/[slug]',
                      query: {
                        slug: product.slug
                      }
                    }}
                    className="pb-3 transition-all hover:text-primary"
                  >
                    {product.title}
                  </Link>
                  {product.selectedAttributes.map(sa => (
                    <div key={sa.attributeId} className="flex gap-1">
                      <span>{sa.attributeTitle}</span>
                      <span>:</span>
                      <span>{sa.selecteds || sa.texts}</span>
                    </div>
                  ))}
                </div>
                <div className="table-cart-body-col col-span-1">
                  {product.quantity}
                </div>
                <div className="table-cart-body-col col-span-2">
                  ${Number(product.price) * 6}
                </div>
                <div className="table-cart-body-col col-span-1">
                  <MdOutlineClose
                    size={40}
                    className="fill-error font-bold mx-auto cursor-pointer transition-all hover:fill-red-600"
                    onClick={() =>
                      dispatch(actions.removeProductToCart({ product, index }))
                    }
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className="col-span-12 border border-gray-200 p-4 rounded ">
          <h4 className="text-gray-800 text-lg mb-4 font-medium uppercase">
            order summary
          </h4>
          <div className="space-y-2">
            <div className="flex justify-between">
              <div>
                <h5 className="text-gray-800 font-medium">
                  Italian shape sofa
                </h5>
                <p className="text-sm text-gray-600">Size: M</p>
              </div>
              <p className="text-gray-600">x3</p>
              <p className="text-gray-800 font-medium">$320</p>
            </div>
            <div className="flex justify-between">
              <div>
                <h5 className="text-gray-800 font-medium">
                  Italian shape sofa
                </h5>
                <p className="text-sm text-gray-600">Size: M</p>
              </div>
              <p className="text-gray-600">x3</p>
              <p className="text-gray-800 font-medium">$320</p>
            </div>
            <div className="flex justify-between">
              <div>
                <h5 className="text-gray-800 font-medium">
                  Italian shape sofa
                </h5>
                <p className="text-sm text-gray-600">Size: M</p>
              </div>
              <p className="text-gray-600">x3</p>
              <p className="text-gray-800 font-medium">$320</p>
            </div>
            <div className="flex justify-between">
              <div>
                <h5 className="text-gray-800 font-medium">
                  Italian shape sofa
                </h5>
                <p className="text-sm text-gray-600">Size: M</p>
              </div>
              <p className="text-gray-600">x3</p>
              <p className="text-gray-800 font-medium">$320</p>
            </div>
          </div>

          <div className="flex justify-between border-b border-gray-200 mt-1 text-gray-800 font-medium py-3 uppercas">
            <p>subtotal</p>
            <p>$1280</p>
          </div>

          <div className="flex justify-between border-b border-gray-200 mt-1 text-gray-800 font-medium py-3 uppercas">
            <p>shipping</p>
            <p>Free</p>
          </div>

          <div className="flex justify-between text-gray-800 font-medium py-3 uppercas">
            <p className="font-semibold">Total</p>
            <p>$1280</p>
          </div>

          <a
            href="#"
            className="block w-full py-3 px-4 text-center text-white bg-primary border border-primary rounded-md hover:bg-transparent hover:text-primary transition font-medium"
          >
            Place order
          </a>
        </div>
      </div>
    </>
  );
}
