import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

// Swiper
import { Autoplay, Navigation } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import 'swiper/css';
import 'swiper/css/autoplay';
import 'swiper/css/navigation';

// Image
import ProductListImage from '@/public/dummy-product-list-image.png';
import CategoryImage from '@/public/dummy-category-image.png';

export default function Home() {
  return (
    <div className="pb-[220px]">
      <Head>
        <title>Matter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Slider */}
      <Swiper slidesPerView={1} modules={[Autoplay]} speed={400} autoplay>
        <SwiperSlide>
          <div
            className="h-[300px] bg-no-repeat bg-cover bg-center md:h-[450px] lg:h-[600px]"
            style={{ backgroundImage: `url('./dummy-slider-image.png')` }}
          >
            <div className="h-full container mx-auto">
              <div className="max-w-[458px] h-full flex flex-col justify-center items-center ml-auto sm:items-start">
                <p className=" text-[25px] sm:text-[35px] text-white md:leading-[80px] md:text-[60px]">
                  Perfume Tips Tricks
                </p>
                <Link
                  href="#"
                  className="leading-[20px] mt-[39px] tracking-[2px] text-[12px] text-white"
                >
                  <span className="pb-2 border-b border-white hover-effect hover:border-orange-500">
                    SHOP NOW
                  </span>
                </Link>
              </div>
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide>
          <div
            className="h-[300px] bg-no-repeat bg-cover bg-center md:h-[450px] lg:h-[600px]"
            style={{ backgroundImage: `url('./dummy-slider-image.png')` }}
          >
            <div className="h-full container mx-auto">
              <div className="max-w-[458px] h-full flex flex-col justify-center items-center ml-auto sm:items-start">
                <p className=" text-[25px] sm:text-[35px] text-white md:leading-[80px] md:text-[60px]">
                  Perfume Tips Tricks
                </p>
                <Link
                  href="#"
                  className="leading-[20px] mt-[39px] tracking-[2px] text-[12px] text-white"
                >
                  <span className="pb-2 border-b border-white hover-effect hover:border-orange-500">
                    SHOP NOW
                  </span>
                </Link>
              </div>
            </div>
          </div>
        </SwiperSlide>
      </Swiper>
      {/* Slider */}
      {/* Products */}
      <div className="container mx-auto mt-[62px] pr-[15px] pl-[15px] md:pr-0 md:pl-0">
        <div className="text-center">
          <p className="leading-[60px] text-[42px]">Featured</p>
        </div>
        <div className="grid grid-cols-12 gap-3 mt:gap-7">
          {[0, 1, 2, 3, 4, 5, 6, 7].map((el, index) => (
            <div
              key={index}
              className="col-span-12 md:col-span-6 lg:col-span-3 mt-10"
            >
              <div className="product-item card">
                <div className="card-body p-0">
                  <figure className="relative">
                    <Image
                      src={ProductListImage}
                      alt="Product list image"
                      className="w-full h-auto"
                    />
                    <div className="product-item-quick-view">
                      <button className="btn w-[75%] leading-[20px] text-[12px] tracking-[2px] bg-[#33333A]">
                        QUICK VIEW
                      </button>
                    </div>
                    <div className="badge absolute top-[10px] left-[10px] bg-orange-500 border-orange-500">
                      <span className="leading-[20px] text-[12px] tracking-[0] uppercase select-none">
                        New
                      </span>
                    </div>
                  </figure>
                  <Link href="/">
                    <div className="pt-[12px]">
                      <p className="leading-[25px] tracking-normal">
                        Pueraria Mirifica And Study Phyto Estrogens
                      </p>
                    </div>
                    <div>
                      <span>$</span>
                      <span>599.00</span>
                    </div>
                  </Link>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
      {/* Products */}
      {/* Categories */}
      <div className="container mx-auto mt-[120px] pr-[15px] pl-[15px] md:pr-0 md:pl-0">
        <div className="text-center">
          <p className="leading-[60px] text-[42px]">Categories</p>
        </div>
        <div className="grid grid-cols-12 gap-3 mt:gap-7">
          {[0, 1, 2, 3].map((el, index) => (
            <div
              key={index}
              className="col-span-12 md:col-span-6 lg:col-span-3 mt-10"
            >
              <div className="product-item card">
                <div className="card-body p-0">
                  <figure className="relative">
                    <Image
                      src={CategoryImage}
                      alt="Product list image"
                      className="w-full h-auto"
                    />
                    <div className="product-item-quick-view">
                      <Link
                        href="/"
                        className="btn w-[75%] leading-[20px] text-[12px] tracking-[2px] bg-[#33333A]"
                      >
                        SHOP NOW
                      </Link>
                    </div>
                    <div className="w-full absolute left-0 bottom-0 mb-[60px] pt-[8px] pb-[8px] bg-white text-center">
                      <span className="leading-[30px] text-[18px] text-[#030303]">
                        Pants
                      </span>
                    </div>
                  </figure>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
      {/* Categories */}
      {/* Recommended */}
      <div className="container mx-auto mt-[120px] pr-[15px] pl-[15px] md:pr-0 md:pl-0">
        <div className="text-center">
          <p className="leading-[60px] text-[42px]">Recommended</p>
        </div>
        <div className="">
          <Swiper
            spaceBetween={10}
            slidesPerView={4}
            modules={[Autoplay, Navigation]}
            speed={400}
            autoplay
            navigation
          >
            {[0, 1, 2, 3, 4, 5, 6, 7, 8, 9].map((el, index) => (
              <SwiperSlide key={index}>
                <div className=" mt-10">
                  <div className="product-item card">
                    <div className="card-body p-0">
                      <figure className="relative">
                        <Image
                          src={ProductListImage}
                          alt="Product list image"
                          className="w-full h-auto"
                        />
                        <div className="product-item-quick-view">
                          <button className="btn w-[75%] leading-[20px] text-[12px] tracking-[2px] bg-[#33333A]">
                            QUICK VIEW
                          </button>
                        </div>
                        <div className="badge absolute top-[10px] left-[10px] bg-orange-500 border-orange-500">
                          <span className="leading-[20px] text-[12px] tracking-[0] uppercase select-none">
                            New
                          </span>
                        </div>
                      </figure>
                      <Link href="/">
                        <div className="pt-[12px]">
                          <p className="leading-[25px] tracking-normal">
                            Pueraria Mirifica And Study Phyto Estrogens
                          </p>
                        </div>
                        <div>
                          <span>$</span>
                          <span>599.00</span>
                        </div>
                      </Link>
                    </div>
                  </div>
                </div>
              </SwiperSlide>
            ))}
          </Swiper>
        </div>
      </div>
      {/* Recommended */}
    </div>
  );
}
