import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import fetchJson from '@/utils/fetchJson';

import { GiHandTruck, GiReceiveMoney } from 'react-icons/gi';
import { RiCustomerServiceLine } from 'react-icons/ri';

import Product1 from '../public/product1.jpg';
import Product2 from '../public/product2.jpg';
import Product3 from '../public/product3.jpg';
import Product4 from '../public/product4.jpg';

import Offer from '../public/offer.jpg';

import { HiHeart, HiMagnifyingGlass, HiStar } from 'react-icons/hi2';
import { ICategory } from '@/interfaces/Category';
import { IProducts } from '@/interfaces/Products';
import { AiFillStar } from 'react-icons/ai';
import { calcDiscountPrice } from '@/utils/helpers';

interface IProps {
  categories: ICategory;
  news: IProducts;
}

export default function Home(props: IProps) {
  return (
    <>
      <Head>
        <title>Matter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className="bg-cover bg-no-repeat bg-center py-36"
        style={{ backgroundImage: `url('banner-bg.jpg')` }}
      >
        <div className="container">
          <h1 className="text-2xl text-gray-800 font-medium mb-4 capitalize md:text-6xl">
            best collection for <br /> home decoration
          </h1>
          <p className="text-sm md:text-base">
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aperiam{' '}
            <br />
            accusantium perspiciatis, sapiente magni eos dolorum ex quos dolores
            odio
          </p>
          <div className="mt-12">
            <Link
              href="#"
              className="bg-primary border border-primary text-white px-8 py-3 font-medium rounded-md hover:bg-transparent hover:text-primary"
            >
              Shop Now
            </Link>
          </div>
        </div>
      </div>
      <div className="container py-16">
        <div className="w-full grid grid-cols-12 gap-6 mx-auto justify-center">
          <div className="col-span-12 border border-primary rounded-sm px-2 py-6 flex justify-center items-center gap-5 md:col-span-4">
            <GiHandTruck size={40} className="fill-primary" />
            <div>
              <h4 className="font-medium capitalize text-lg">Free Shipping</h4>
              <p className="text-gray-500 text-sm">Order over $200</p>
            </div>
          </div>
          <div className="col-span-12 border border-primary rounded-sm px-2 py-6 flex justify-center items-center gap-5 md:col-span-4">
            <GiReceiveMoney size={40} className="fill-primary" />
            <div>
              <h4 className="font-medium capitalize text-lg">Money Returns</h4>
              <p className="text-gray-500 text-sm">30 days money returs</p>
            </div>
          </div>
          <div className="col-span-12 border border-primary rounded-sm px-2 py-6 flex justify-center items-center gap-5 md:col-span-4">
            <RiCustomerServiceLine size={40} className="fill-primary" />

            <div>
              <h4 className="font-medium capitalize text-lg">24/7 Support</h4>
              <p className="text-gray-500 text-sm">Customer support</p>
            </div>
          </div>
        </div>
      </div>
      {props.categories.data.length > 0 && (
        <div className="container py-16">
          <h2 className="text-2xl font-medium text-gray-800 uppercase mb-6">
            shop by category
          </h2>
          <div className="grid grid-cols-12 gap-3">
            {props.categories.data.map(category => (
              <div
                key={category._id}
                className="col-span-12 relative rounded-sm overflow-hidden group md:col-span-4"
              >
                <Image
                  src={category.image}
                  alt={category.alt || 'Matter'}
                  width={350}
                  height={500}
                  className="w-full h-full object-cover"
                />
                <Link
                  href={{
                    pathname: '/category/[slug]',
                    query: {
                      slug: category.slug
                    }
                  }}
                  className="absolute inset-0 bg-black bg-opacity-40 flex items-center justify-center text-xl text-white font-roboto font-medium group-hover:bg-opacity-60 transition"
                >
                  {category.name}
                </Link>
              </div>
            ))}
          </div>
        </div>
      )}
      {props.news.data.length > 0 && (
        <div className="container pb-16">
          <h2 className="text-2xl font-medium text-gray-800 uppercase mb-6">
            top new arrival
          </h2>
          <div className="grid grid-cols-12 gap-6">
            {props.news.data.map(newProduct => (
              <div
                key={newProduct._id}
                className="col-span-12 bg-white shadow rounded overflow-hidden group sm:col-span-6 md:col-span-3"
              >
                <div className="relative">
                  <Image
                    src={newProduct.thumbnail}
                    width={350}
                    height={271}
                    alt={newProduct.alt}
                    className="w-full h-full object-cover"
                  />
                  <div
                    className="absolute inset-0 bg-black bg-opacity-40 flex items-center 
                    justify-center gap-2 opacity-0 group-hover:opacity-100 transition"
                  >
                    <Link
                      href={{
                        pathname: '/product/[slug]',
                        query: {
                          slug: newProduct.slug
                        }
                      }}
                      className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                    >
                      <HiMagnifyingGlass />
                    </Link>
                    <a
                      href="#"
                      className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                      title="add to wishlist"
                    >
                      <HiHeart />
                    </a>
                  </div>
                </div>
                <div className="pt-4 pb-3 px-4">
                  <Link
                    href={{
                      pathname: '/product/[slug]',
                      query: { slug: newProduct.slug }
                    }}
                  >
                    <p className="w-[100%] h-[40px] line-clamp-2 font-medium text-sm mb-2 text-gray-800 hover:text-primary transition">
                      {newProduct.title}
                    </p>
                  </Link>
                  <div className="flex items-baseline mb-1 space-x-2">
                    {newProduct.discountPercentage > 0 ? (
                      <>
                        <p className="text-xl text-primary font-semibold">
                          $
                          {calcDiscountPrice(
                            newProduct.price,
                            newProduct.discountPercentage
                          )}
                        </p>
                        <p className="text-sm text-gray-400 line-through">
                          ${newProduct.price}
                        </p>
                      </>
                    ) : (
                      <>
                        <p className="text-xl text-primary font-semibold">
                          ${newProduct.price}
                        </p>
                      </>
                    )}
                  </div>
                  <div className="flex items-center">
                    <div className="flex gap-1 text-sm">
                      {[0, 1, 2, 3, 4].map(index => (
                        <span key={index}>
                          <AiFillStar
                            className={`${
                              newProduct.rating >= index + 1 &&
                              'fill-yellow-400'
                            }`}
                          />
                        </span>
                      ))}
                    </div>
                    <div className="text-xs text-gray-500 ml-3">(0)</div>
                  </div>
                </div>
                <Link
                  href={`/product/${newProduct.slug}`}
                  className="block w-full py-1 text-center text-white bg-primary border border-primary rounded-b hover:bg-transparent hover:text-primary transition"
                >
                  Review Product
                </Link>
              </div>
            ))}
          </div>
        </div>
      )}
      <div className="container pb-16">
        <Link href="#">
          <Image src={Offer} alt="ads" className="w-full" />
        </Link>
      </div>
      <div className="container pb-16">
        <h2 className="text-2xl font-medium text-gray-800 uppercase mb-6">
          recomended for you
        </h2>
        <div className="grid grid-cols-12 gap-6">
          <div className="col-span-12 bg-white shadow rounded overflow-hidden group sm:col-span-6 md:col-span-3">
            <div className="relative">
              <Image src={Product1} alt="product 1" className="w-full" />
              <div
                className="absolute inset-0 bg-black bg-opacity-40 flex items-center 
                    justify-center gap-2 opacity-0 group-hover:opacity-100 transition"
              >
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="view product"
                >
                  <HiMagnifyingGlass />
                </a>
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="add to wishlist"
                >
                  <HiHeart />
                </a>
              </div>
            </div>
            <div className="pt-4 pb-3 px-4">
              <a href="#">
                <h4 className="uppercase font-medium text-xl mb-2 text-gray-800 hover:text-primary transition">
                  Guyer Chair
                </h4>
              </a>
              <div className="flex items-baseline mb-1 space-x-2">
                <p className="text-xl text-primary font-semibold">$45.00</p>
                <p className="text-sm text-gray-400 line-through">$55.90</p>
              </div>
              <div className="flex items-center">
                <div className="flex gap-1 text-sm text-yellow-400">
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                </div>
                <div className="text-xs text-gray-500 ml-3">(150)</div>
              </div>
            </div>
            <a
              href="#"
              className="block w-full py-1 text-center text-white bg-primary border border-primary rounded-b hover:bg-transparent hover:text-primary transition"
            >
              Add to cart
            </a>
          </div>
          <div className="col-span-12 bg-white shadow rounded overflow-hidden group sm:col-span-6 md:col-span-3">
            <div className="relative">
              <Image src={Product2} alt="product 1" className="w-full" />
              <div
                className="absolute inset-0 bg-black bg-opacity-40 flex items-center 
                    justify-center gap-2 opacity-0 group-hover:opacity-100 transition"
              >
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="view product"
                >
                  <HiMagnifyingGlass />
                </a>
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="add to wishlist"
                >
                  <HiHeart />
                </a>
              </div>
            </div>
            <div className="pt-4 pb-3 px-4">
              <a href="#">
                <h4 className="uppercase font-medium text-xl mb-2 text-gray-800 hover:text-primary transition">
                  Bed King Size
                </h4>
              </a>
              <div className="flex items-baseline mb-1 space-x-2">
                <p className="text-xl text-primary font-semibold">$45.00</p>
                <p className="text-sm text-gray-400 line-through">$55.90</p>
              </div>
              <div className="flex items-center">
                <div className="flex gap-1 text-sm text-yellow-400">
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                </div>
                <div className="text-xs text-gray-500 ml-3">(150)</div>
              </div>
            </div>
            <a
              href="#"
              className="block w-full py-1 text-center text-white bg-primary border border-primary rounded-b hover:bg-transparent hover:text-primary transition"
            >
              Add to cart
            </a>
          </div>
          <div className="col-span-12 bg-white shadow rounded overflow-hidden group sm:col-span-6 md:col-span-3">
            <div className="relative">
              <Image src={Product3} alt="product 1" className="w-full" />
              <div
                className="absolute inset-0 bg-black bg-opacity-40 flex items-center 
                    justify-center gap-2 opacity-0 group-hover:opacity-100 transition"
              >
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="view product"
                >
                  <HiMagnifyingGlass />
                </a>
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="add to wishlist"
                >
                  <HiHeart />
                </a>
              </div>
            </div>
            <div className="pt-4 pb-3 px-4">
              <a href="#">
                <h4 className="uppercase font-medium text-xl mb-2 text-gray-800 hover:text-primary transition">
                  Couple Sofa
                </h4>
              </a>
              <div className="flex items-baseline mb-1 space-x-2">
                <p className="text-xl text-primary font-semibold">$45.00</p>
                <p className="text-sm text-gray-400 line-through">$55.90</p>
              </div>
              <div className="flex items-center">
                <div className="flex gap-1 text-sm text-yellow-400">
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                </div>
                <div className="text-xs text-gray-500 ml-3">(150)</div>
              </div>
            </div>
            <a
              href="#"
              className="block w-full py-1 text-center text-white bg-primary border border-primary rounded-b hover:bg-transparent hover:text-primary transition"
            >
              Add to cart
            </a>
          </div>
          <div className="col-span-12 bg-white shadow rounded overflow-hidden group sm:col-span-6 md:col-span-3">
            <div className="relative">
              <Image src={Product4} alt="product 1" className="w-full" />
              <div
                className="absolute inset-0 bg-black bg-opacity-40 flex items-center 
                    justify-center gap-2 opacity-0 group-hover:opacity-100 transition"
              >
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="view product"
                >
                  <HiMagnifyingGlass />
                </a>
                <a
                  href="#"
                  className="text-white text-lg w-9 h-8 rounded-full bg-primary flex items-center justify-center hover:bg-gray-800 transition"
                  title="add to wishlist"
                >
                  <HiHeart />
                </a>
              </div>
            </div>
            <div className="pt-4 pb-3 px-4">
              <a href="#">
                <h4 className="uppercase font-medium text-xl mb-2 text-gray-800 hover:text-primary transition">
                  Mattrass X
                </h4>
              </a>
              <div className="flex items-baseline mb-1 space-x-2">
                <p className="text-xl text-primary font-semibold">$45.00</p>
                <p className="text-sm text-gray-400 line-through">$55.90</p>
              </div>
              <div className="flex items-center">
                <div className="flex gap-1 text-sm text-yellow-400">
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                  <span>
                    <HiStar />
                  </span>
                </div>
                <div className="text-xs text-gray-500 ml-3">(150)</div>
              </div>
            </div>
            <a
              href="#"
              className="block w-full py-1 text-center text-white bg-primary border border-primary rounded-b hover:bg-transparent hover:text-primary transition"
            >
              Add to cart
            </a>
          </div>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const categories = await fetchJson(
    `${process.env.API_BASE_URL}/api/category`,
    { method: 'GET' }
  );

  const news = await fetchJson(
    `${process.env.API_BASE_URL}/api/products?limit=4&skip=0`,
    { method: 'GET' }
  );

  return {
    props: {
      categories,
      news
    }
  };
}
