#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️ Starting Husky controls for pre-commit hook...';

# Check tsconfig standarts
npm run check-types || {
    echo '💥 TypeScript check failed';
    exit 1;
}

# Check eslint standarts
npm run check-lint || {
    echo '💥 ESLint check failed';
    exit 1;
}
